openapi: 3.0.0
info:
  title: Persons Service API
  description: Connections via geolocation
  version: 1.0.0
paths:
  /persons:
    post:
      summary: Create a new person
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Person'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Person'
    get:
      summary: Retrieve all persons
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Person'
  /persons/{person_id}:
    get:
      summary: Retrieve a specific person
      parameters:
        - name: person_id
          in: path
          description: Unique ID for a given Person
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Person'
components:
  schemas:
    Person:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        age:
          type: integer